
analyzer:
  errors:
    public_member_api_docs: ignore 
    lines_longer_than_80_chars: ignore
    constant_identifier_names: ignore
    comment_references: ignore
include: package:very_good_analysis/analysis_options.yaml
linter:
 
  rules:
